### ISSUE TITLE
README

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [upperlevel/uppercore#15]
I would recommend adding a readme and some docs

**Comment by xXXIMMATTHEWXXx** [comment]
Also a license

**Comment by xXXIMMATTHEWXXx** [comment]
Just saying, I would be happy to write some stuff you guys!

**Comment by SnowyCoder** [comment]
License added (MIT)
We were already thinking about creating the docs, but now we are quite a bit occupied and we don't have a lot of time to dedicate to the project (see [Openverse](https://github.com/upperlevel/openverse/tree/dev)), however we will be creating the documentation for this project.
If you want to add some for us we would be happy to view it!

**Comment by xXXIMMATTHEWXXx** [comment]
Ill be happy to! Ill start later
!!
